### GENERAL ###

# Update 'control key' to <Ctrl-a> since it is easier to reach
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Command delay? No thank you, shorten it here
set -sg escape-time 1

# Allow mouse operations for scroll, resize, and select
set -g mouse on

# allow sending Ctrl-A to terminal (readline start-of-line)
bind a send-prefix


### KEY BINDINGS ###

# Allow us to relaod our tmux configuration while using tmux
bind r source-file ~/.tmux.conf \; display-message "tmux.conf Reloaded!"

# Use the vertical and horizontal symbols to split the screen and use current directory
bind L split-window -h -c "#{pane_current_path}"
bind J split-window -v -c "#{pane_current_path}"

# Because l is used in vim-tmux-navigator, need a new last-window binding
bind "'" last-window  # new binding for toggle window

# Use X to close window 
bind X confirm-before -p "kill-window #W? (y/n)" kill-window

# Pane resizing
bind -r + resize-pane -U
bind -r - resize-pane -D
bind -r < resize-pane -L
bind -r > resize-pane -R
bind -r Up resize-pane -U 10
bind -r Down resize-pane -D 10
bind -r Left resize-pane -L 10
bind -r Right resize-pane -R 10

# Use b to go to previous window (since p is used for paste in copy mode)
bind b previous-window


### COPY MODE ###
# vim
setw -g mode-keys vi                                    # set vi mode for copy-mode
bind -T copy-mode-vi Escape send-keys -X cancel         # use esc to exit copy-mode
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle  # begin rectangle selection C-v
bind -T copy-mode-vi v send-keys -X begin-selection     # begin selection with v
bind -T copy-mode-vi V send-keys -X select-line         # begin line selection with V
bind -T copy-mode-vi y send-keys -X copy-selection      # yank text
unbind p                                                # unbind so we can paste using p
bind p paste-buffer                                     # paste using p

# send yanked text to system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"


### PLUGINS ###

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
